---
name: nox

"on":
    workflow_call:

jobs:
    nox:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            include:
              - session: lint
                python-versions: "3.13"
              - session: format
                python-versions: "3.13"
              - session: spelling
                python-versions: "3.13"
              - session: build
                python-versions: "3.13"
        name: "Run nox ${{ matrix.session }} session"
        steps:
          - name: Check out repo
            uses: actions/checkout@v5
          - name: Setup nox
            uses: wntrblm/nox@2025.10.16
            with:
              python-versions: "${{ matrix.python-versions }}"
          - name: "Run nox -s ${{ matrix.session }}"
            run: |
              nox -s "${{ matrix.session }}"
